name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: ./.github/workflows/T.yml@v1
    with:
      os: 'macos-latest'
      version: '10, 12, 14, 16, 18, 19'
